export const Images = {
  trophies: require('./trophies.png'),
  signinWithGoogle: require('./signinWithGoogle.png'),
  signinWithEmail: require('./signWithEmail.png'),
  back: require('./back.png'),
  eyeClosed: require('./eye.png'),
  eyeOpen: require('./eyeOpen.png'),
  avatarPlaceholder: require('./avatarPlaceholder.png'),
  camera: require('./camera.png'),
  avatar1: require('./Avatars1.png'),
  avatar2: require('./Avatars2.png'),
  avatar3: require('./Avatars3.png'),
  avatar4: require('./Avatars4.png'),
  avatar5: require('./Avatars5.png'),
  avatar6: require('./Avatars6.png'),
  avatar7: require('./Avatars7.png'),
  avatar8: require('./Avatars8.png'),
  avatar9: require('./Avatars9.png'),
  avatar10: require('./Avatars10.png'),
  avatar11: require('./Avatars11.png'),
  cameraTransparent: require('./camera1.png'),
  image: require('./image.png'),
  search: require('./search.png'),
  checkmark: require('./checkmark.png'),
};
